feat: set player bar size same as bottomnavview
ArtemShishko/internship pull request #110
Opened 2021-11-26 14:00 UTC by ArtemShishko

2021-11-26 14:02 UTC, ArtemShishko commented
UI changes:
![Screenshot_20211126-165727_Flowdy](https://user-images.githubusercontent.com/44274078/143592270-708e1a87-808d-4cec-9083-e79cde96fa51.jpg)

2021-11-29 09:38 UTC, Vladuken requested changes

2021-11-29 09:38 UTC, Vladuken commented on app/src/main/res/layout/player_bar.xml
> +        android:layout_width="52dp"
make it 0dp for height and also you can set aspect ratio 1:1 here

2021-11-29 09:38 UTC, Vladuken commented on app/src/main/res/values/dimens.xml
> +    <dimen name="player_bar_cover">52dp</dimen>
So you could remove this dimension

2021-11-29 11:51 UTC, merged